## Numpy

NumPy stands for Numerical Python, is an open-source Python library that provides support for large, multi-dimensional arrays and matrices.

It also have a collection of high-level mathematical functions to operate on arrays. It was created by Travis Oliphant in 2005.

Features of NumPy

NumPy has various features which make them popular over lists.

Some of these important features include:

- A powerful N-dimensional array object
- Sophisticated (broadcasting) functions
- Tools for integrating C/C++ and Fortran code
- Useful linear algebra, Fourier transform, and random number capabilities

In [8]:
import numpy as np

**Creation of 1D Array**

In [10]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


**Creation of 2D Array**

In [12]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


**Creation of 3D Array**

In [10]:
c = np.array([[[1,2,3]],
              
              [[4,5,6]],
              
              [[7,8,9]]])
print(c)

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


**Shape**

In [49]:
print(c.shape)

(3, 1, 3)


**Size**

In [18]:
print(b.size)

6


**Dimension**

In [20]:
print(a.ndim)

1


**Indexing**

## Common Functions

**zeros**

In [66]:
print(np.zeros([3,2,5]))

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


**ones**

In [71]:
print(np.ones([4,2]))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


**Full Numpy Array**

In [76]:
print(np.full([3,2],1))

[[1 1]
 [1 1]
 [1 1]]


**Empty**

In [88]:
print(np.empty([2,3]))

[[9.34577196e-307 9.34598246e-307 1.60218491e-306]
 [1.69119873e-306 1.24611673e-306 1.16824951e-307]]


## **Reshaping**

**1D to 2D**

In [94]:
a = np.array([1,2,3,4,5,6])
a2d = a.reshape(2,3)
print(a2d)

[[1 2 3]
 [4 5 6]]


**1D to 3D**

In [185]:
a3d = a.reshape(2,2,3)
print(a3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


**2D to 3D**

In [173]:
a3d = a2d.reshape(2,1,3)
print(a3d)

[[[1 2 3]]

 [[4 5 6]]]


**3D to 1D**

In [132]:
p,m,n = a3d.shape
total = m*n*p
print(a3d.reshape(total))

[1 2 3 4 5 6]


In [119]:
print(a3d.reshape(-1))

[1 2 3 4 5 6]


**3D to 2D**

In [156]:

a3d = np.array([[[1, 2, 3], 
                    [4, 5, 6]], 
                   
                   [[7, 8, 9], 
                    [10, 11, 12]]])

print("Original 3D array:")
print(a3d)


Original 3D array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [162]:
print(a3d.reshape(-1,1))
print(a3d.reshape(-1,1).ndim)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
2


In [152]:
d,m,n = a3d.shape
total = d*m,n
# Reshape the 3D array to 2D by combining the first two dimensions
print(a3d.reshape(total))
print(a3d.reshape(total).ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2


In [154]:
d,m,n = a3d.shape
total = d,m*n
# Reshape the 3D array to 2D by combining the last two dimensions
print(a3d.reshape(total))
print(a3d.reshape(total).ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
2


In [164]:
print(a3d.reshape(1,-1))
print(a3d.reshape(1,-1).ndim)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
2


The key difference between reshape(-1, 1) and reshape(1, -1) is the shape of the resulting array. reshape(-1, 1) results in an array with a single column and multiple rows (a column vector), while reshape(1, -1) results in an array with a single row and multiple columns (a row vector).


### Indexing

Indexing is used to access individual elements of an array.

#### 1D Array Indexing:



In [28]:
import numpy as np

# Creating a 1D array
arr_1d = np.array([10, 20, 30, 40, 50])

# Accessing elements
print("Element at index 0:", arr_1d[0]) 
print("Element at index 3:", arr_1d[3]) 

Element at index 0: 10
Element at index 3: 40



#### 2D Array Indexing:




In [30]:
# Creating a 2D array
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

# Accessing elements
print("Element at row 1, column 2:", arr_2d[1, 2])  # Output: 6

# Accessing rows
print("Row 0:", arr_2d[0])  # Output: [1 2 3]

# Accessing columns
print("Column 1:", arr_2d[:, 1])  # Output: [2 5 8]


Element at row 1, column 2: 6
Row 0: [1 2 3]
Column 1: [2 5 8]




### Slicing

Slicing is used to access a range of elements.




In [38]:
#1D Array Slicing:

print("Elements from index 1 to 3:", arr_1d[1:4])  # Output: [20 30 40]

#2D Array Slicing:

print("Subarray with rows 0 to 1 and columns 1 to 2:\n", arr_2d[0:2, 1:3])  # Output: [[2 3] [5 6]]

Elements from index 1 to 3: [20 30 40]
Subarray with rows 0 to 1 and columns 1 to 2:
 [[2 3]
 [5 6]]



### Concatenating

Concatenation is used to join arrays along an existing axis.

#### Concatenating 1D Arrays:



In [ ]:
# Creating two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenating arrays
arr_concat = np.concatenate((arr1, arr2))
print("Concatenated 1D array:", arr_concat)  # Output: [1 2 3 4 5 6]






#

In [ ]:
#### Concatenating 2D Arrays:

# Creating two 2D arrays
arr1_2d = np.array([[1, 2], [3, 4]])
arr2_2d = np.array([[5, 6], [7, 8]])

# Concatenating arrays along rows (axis=0)
arr_concat_2d = np.concatenate((arr1_2d, arr2_2d), axis=0)
print("Concatenated 2D array along rows:\n", arr_concat_2d)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

# Concatenating arrays along columns (axis=1)
arr_concat_2d_cols = np.concatenate((arr1_2d, arr2_2d), axis=1)
print("Concatenated 2D array along columns:\n", arr_concat_2d_cols)
# Output:
# [[1 2 5 6]
#  [3 4 7 8]]

### Splitting

Splitting is used to split an array into multiple subarrays.

In [ ]:
### Splitting 1D Array:

# Splitting a 1D array
arr_split_1d = np.array([1, 2, 3, 4, 5, 6])
split_1d = np.array_split(arr_split_1d, 3)
print("Splitting 1D array into 3 parts:", split_1d)


#### Splitting 2D Array:

# Splitting a 2D array
arr_split_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Splitting along rows (axis=0)
split_2d_rows = np.array_split(arr_split_2d, 3, axis=0)
print("Splitting 2D array into 3 parts along rows:\n", split_2d_rows)


# Splitting along columns (axis=1)
split_2d_cols = np.array_split(arr_split_2d, 3, axis=1)
print("Splitting 2D array into 3 parts along columns:\n", split_2d_cols)
# Output:
# [array([[1],
#         [4],
#         [7]]), 
#  array([[2],
#         [5],
#         [8]]), 
#  array([[3],
#         [6],
#         [9]])]
```
