## Broadcasting in NumPy


Broadcasting is a powerful mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes. It works by stretching the smaller array across the larger array so that they have compatible shapes.

### Working

When performing operations on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions and works its way backward. Two dimensions are compatible when:
- They are equal, or
- One of them is 1

If the shapes are not compatible, NumPy throws a `ValueError`.


### Example of Broadcasting

array `A` of shape (3, 1) and an array `B` of shape (1, 4):




In [5]:
import numpy as np

A = np.array([[1], [2], [3]])  # Shape (3, 1)
B = np.array([[4, 5, 6, 7]])    # Shape (1, 4)

##When we add these two arrays, NumPy will broadcast `A` and `B` to a common shape

C = A + B
print(C)

[[ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]]


### Step-by-Step Broadcasting:

1. `A` is broadcasted from (3, 1) to (3, 4):
   
   [[1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3]]
   

2. `B` is broadcasted from (1, 4) to (3, 4):
   
   [[4, 5, 6, 7],
    [4, 5, 6, 7],
    [4, 5, 6, 7]]
   

3. The resulting array `C` is the element-wise sum of the broadcasted `A` and `B`:
   
   [[ 5,  6,  7,  8],
    [ 6,  7,  8,  9],
    [ 7,  8,  9, 10]]
   


### Why is Broadcasting Useful?

- **Efficiency:** Broadcasting eliminates the need to create copies of arrays for element-wise operations, saving memory and improving performance.
- **Simplicity:** It allows for writing more concise and readable code.

### Note

Remember that broadcasting follows strict rules for compatibility. Always ensure that the shapes of your arrays align according to these rules to avoid errors.
